Club.create!([
  {name: "Association for Computing Machinery ", president: "Akshay Bakshi", year: "1975", email: "acm@ucla.edu", website: "http://acm.cs.ucla.edu/", description: "Founded in 1947, the Association for Computing Machinery, a national organization, is a major force in advancing the skills of information technology professionals and students worldwide. Today, its 75,000 members and the public turn to ACM for the industry's leading Portal to Computing Literature, authoritative publications and pioneering conferences, providing leadership for the 21st century.", joining: "Anybody interested in the field of Computer Science, with theoretical and applied interests, is welcome to join ACM. If you have a passion for technology and are interested in putting your skills to use, you are strongly encouraged to join. We want enthusiastic members like you!\r\n", deleted_at: nil},
  {name: "American Institute of Aeronautics and Astronautics", president: "Aurora Garcia", year: "", email: "aiaaucla@gmail.com", website: "http://aiaa.seas.ucla.edu/", description: "The American Institute of Aeronautics and Astronautics (AIAA) is a professional aerospace engineering organization. With more than 31,000 members worldwide, AIAA links professionals, educators, and students together to advance the aerospace industry. The UCLA Chapter in particular focuses on enriching hands-on experiences for student engineers, building bridges between students and industry professionals, and expanding this community of one-of-a-kind professions.\r\n\r\nAIAA's UCLA Student Chapter offers exciting projects and events for anyone interested in the aerospace industry. The Rocket Project at UCLA, Design/Build/Fly (DBF), and Unmanned Air Vehicle (UAV) are all AIAA engineering projects active throughout the year. Each project is entirely student run, and welcomes passionate engineers who love to learn and grow with dedicated and ambitious teammates. AIAA also holds fun professional networking events! In the past, we've hosted successful events such as ATK Company Tour, Lockheed Martin Game night, MAE Alumni Networking Night, and numerous company information nights. We also have social events bringing students to the Miramar Air show, kayaking, BBQs, and trips to the California Science Center. Students do no need to be aerospace engineering majors to join AIAA, and in fact we welcome students from all majors.", joining: "For more information about becoming a part of the AIAA UCLA Chapter, please visit our website and attend the AIAA Kick-off Meeting in the Fall!", deleted_at: nil},
  {name: "American Institute of Chemical Engineers", president: "Charlie Glavin", year: "1978", email: "aiche@seas.ucla.edu", website: "http://www.aicheucla.com/", description: "AIChE at UCLA is a professional organization for chemical engineers at UCLA. We focus on professional mentorship, industry and peer networking, and career development workshops and activities. The goal of our organization is to help students discover opportunities for chemical engineers and to help students prepare for careers in industry or academia.", joining: "Attend any AIChE at UCLA event and ask an officer about membership. Also be sure to sign up with the national organization at www.aiche.org/community/membership.", deleted_at: nil},
  {name: "American Indian Science and Engineering Society ", president: "Omar Leyva", year: "1990", email: "ucla.aises@gmail.com", website: "https://sites.google.com/site/uclaaises/home", description: "Entering its nineteenth year on campus, AISES strives to encourage American Indians to pursue careers as scientists and engineers while preserving their cultural heritage. The goal of AISES is to substantially increase the representation of American Indians and Alaskan Natives in engineering, science, and other related technology disciplines. AISES devotes most of its energy to its outreach event where members put on engineering workshops for students from local middle schools, other wise known as Youth Motivation Day. In addition, AISES also conducts tutoring at local schools to help students succeed in math. Serving as mentors and role models for younger students enables UCLA AISES students to further develop professionalism and responsibility while maintaining a high level of academic excellence and increasing cultural awareness.", joining: "Come to our meetings in the fall! Email us or visit our website to find out when the first meeting is.", deleted_at: nil},
  {name: "Association for Computing Machinery ", president: "Akshay Bakshi", year: "1975", email: "acm@ucla.edu", website: "http://acm.cs.ucla.edu/", description: "Founded in 1947, the Association for Computing Machinery, a national organization, is a major force in advancing the skills of information technology professionals and students worldwide. Today, its 75,000 members and the public turn to ACM for the industry's leading Portal to Computing Literature, authoritative publications and pioneering conferences, providing leadership for the 21st century.", joining: "Anybody interested in the field of Computer Science, with theoretical and applied interests, is welcome to join ACM. If you have a passion for technology and are interested in putting your skills to use, you are strongly encouraged to join. We want enthusiastic members like you!\r\n", deleted_at: nil},
  {name: "American Institute of Aeronautics and Astronautics", president: "Aurora Garcia", year: "", email: "aiaaucla@gmail.com", website: "http://aiaa.seas.ucla.edu/", description: "The American Institute of Aeronautics and Astronautics (AIAA) is a professional aerospace engineering organization. With more than 31,000 members worldwide, AIAA links professionals, educators, and students together to advance the aerospace industry. The UCLA Chapter in particular focuses on enriching hands-on experiences for student engineers, building bridges between students and industry professionals, and expanding this community of one-of-a-kind professions.\r\n\r\nAIAA's UCLA Student Chapter offers exciting projects and events for anyone interested in the aerospace industry. The Rocket Project at UCLA, Design/Build/Fly (DBF), and Unmanned Air Vehicle (UAV) are all AIAA engineering projects active throughout the year. Each project is entirely student run, and welcomes passionate engineers who love to learn and grow with dedicated and ambitious teammates. AIAA also holds fun professional networking events! In the past, we've hosted successful events such as ATK Company Tour, Lockheed Martin Game night, MAE Alumni Networking Night, and numerous company information nights. We also have social events bringing students to the Miramar Air show, kayaking, BBQs, and trips to the California Science Center. Students do no need to be aerospace engineering majors to join AIAA, and in fact we welcome students from all majors.", joining: "For more information about becoming a part of the AIAA UCLA Chapter, please visit our website and attend the AIAA Kick-off Meeting in the Fall!", deleted_at: nil}
])

ClubType.create!([
  {name: "Honor Society"},
  {name: "Project"},
  {name: "Professional"},
  {name: "Social"},
  {name: "Service"},
  {name: "Greek"}
])

Major.create!([
  {name: "All"},
  {name: "Aero/Mech"},
  {name: "BioE"},
  {name: "Chemical"},
  {name: "Civil/Enviro"},
  {name: "CS"},
  {name: "CSE"},
  {name: "Electrical"},
  {name: "Materials"}
])

User.create!([
  {username: "super_user", email: "shannon.tan1994@gmail.com", password: "clubon", site_admin: true, deleted_at: nil}
])
